In [1]:
import pandas as pd

In [2]:
dat = pd.read_csv("/Users/ruyiyang/Desktop/coding_discussions_ppol564_fall2020/03_coding_discussion/chicago_summer_2018_crime_data.csv")

In [3]:
dat.head()

,month,day,year,day_of_week,description,location_description,block,primary_type,district,ward,arrest,domestic,latitude,longitude
0,8,4,2018,Saturday,FROM BUILDING,APARTMENT,039XX W WASHINGTON BLVD,THEFT,11,28.0,False,False,NaN,NaN
1,7,26,2018,Thursday,POCKET-PICKING,RESTAURANT,005XX W MADISON ST,THEFT,1,42.0,False,False,NaN,NaN
2,6,24,2018,Sunday,BOGUS CHECK,GROCERY FOOD STORE,004XX E 34TH ST,DECEPTIVE PRACTICE,2,4.0,False,False,NaN,NaN
3,6,13,2018,Wednesday,SIMPLE,RESIDENCE,098XX S EXCHANGE AVE,ASSAULT,4,10.0,False,True,NaN,NaN
4,6,14,2018,Thursday,TO VEHICLE,STREET,001XX S WALLER AVE,CRIMINAL DAMAGE,15,29.0,False,False,NaN,NaN

- the **_unit of observation_** is the crime type (i.e. `primary_type`),
- the **_column variables_** corresponds with the **_day of the month_**, and
- **_each cell_** is populated by the **_proportion of times that crime type was committed over all days of the month_**
    + For example, assume there were just two days in a month and 2 thefts were committed on the first day, and 1 on the second day, then the _proportion_ of thefts committed on the first day would be .66 and .33 on the second day).

Make sure that:

- all missing values are filled with zeros. Zeros in this case means no crimes were committed that day;
- the data is rounded to the second decimal place; and
- the data frame is printed at the end of the notebook.

In [31]:
dat.groupby(["primary_type","day"]).size()

primary_type       day
ARSON              1       4
                   2       3
                   3       3
                   4       2
                   5       4
                          ..
WEAPONS VIOLATION  27     46
                   28     51
                   29     66
                   30     56
                   31     39
Length: 802, dtype: int64

In [34]:
dat.groupby(["primary_type"]).size()

primary_type
ARSON                                  112
ASSAULT                               5635
BATTERY                              14111
BURGLARY                              3390
CONCEALED CARRY LICENSE VIOLATION       44
CRIM SEXUAL ASSAULT                    430
CRIMINAL DAMAGE                       7931
CRIMINAL TRESPASS                     1779
DECEPTIVE PRACTICE                    4684
GAMBLING                               115
HOMICIDE                               172
HUMAN TRAFFICKING                        2
INTERFERENCE WITH PUBLIC OFFICER       374
INTIMIDATION                            54
KIDNAPPING                              47
LIQUOR LAW VIOLATION                    83
MOTOR VEHICLE THEFT                   2608
NARCOTICS                             3047
NON-CRIMINAL                             8
NON-CRIMINAL (SUBJECT SPECIFIED)         2
OBSCENITY                               21
OFFENSE INVOLVING CHILDREN             532
OTHER OFFENSE                         4478
PROSTITUTION                           185
PUBLIC INDECENCY                         5
PUBLIC PEACE VIOLATION                 372
ROBBERY                               2680
SEX OFFENSE                            276
STALKING                                54
THEFT                                18541
WEAPONS VIOLATION                     1601
dtype: int64

primary_type       day
ARSON              1      0.035714
                   2      0.026786
                   3      0.026786
                   4      0.017857
                   5      0.035714
                            ...
WEAPONS VIOLATION  27     0.028732
                   28     0.031855
                   29     0.041224
                   30     0.034978
                   31     0.024360
Length: 802, dtype: float64

In [39]:
#create new data involving cell values

datcell =dat.groupby(["primary_type","day"]).size()/dat.groupby(["primary_type"]).size()
datcell1 = datcell.reset_index().round(2)
datcell1

          primary_type  day     0
0                ARSON    1  0.04
1                ARSON    2  0.03
2                ARSON    3  0.03
3                ARSON    4  0.02
4                ARSON    5  0.04
..                 ...  ...   ...
797  WEAPONS VIOLATION   27  0.03
798  WEAPONS VIOLATION   28  0.03
799  WEAPONS VIOLATION   29  0.04
800  WEAPONS VIOLATION   30  0.03
801  WEAPONS VIOLATION   31  0.02

[802 rows x 3 columns]

In [47]:
#change column name
datcell2 = datcell1.rename(columns={0: "percent"})
datcell2

          primary_type  day  percent
0                ARSON    1     0.04
1                ARSON    2     0.03
2                ARSON    3     0.03
3                ARSON    4     0.02
4                ARSON    5     0.04
..                 ...  ...      ...
797  WEAPONS VIOLATION   27     0.03
798  WEAPONS VIOLATION   28     0.03
799  WEAPONS VIOLATION   29     0.04
800  WEAPONS VIOLATION   30     0.03
801  WEAPONS VIOLATION   31     0.02

[802 rows x 3 columns]

In [49]:
#make table from long to wide
table = pd.pivot_table(datcell2, values='percent', index=['primary_type'],
                    columns=['day'])
table

day,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
primary_type,,,,,,,,,,,,,,,,,,,,,
ARSON,0.04,0.03,0.03,0.02,0.04,0.05,0.04,0.04,0.02,0.02,...,0.04,0.01,0.05,0.01,0.02,0.01,0.03,0.05,0.03,0.03
ASSAULT,0.04,0.03,0.03,0.04,0.04,0.03,0.03,0.03,0.03,0.03,...,0.03,0.03,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.02
BATTERY,0.04,0.04,0.03,0.04,0.03,0.03,0.03,0.03,0.03,0.03,...,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.02
BURGLARY,0.04,0.03,0.03,0.03,0.03,0.04,0.03,0.03,0.03,0.03,...,0.04,0.03,0.04,0.03,0.03,0.04,0.03,0.03,0.03,0.02
CONCEALED CARRY LICENSE VIOLATION,0.05,0.02,0.05,0.05,0.02,0.05,0.05,NaN,0.02,0.05,...,0.02,NaN,0.05,0.07,0.07,0.02,0.02,NaN,0.02,0.05
CRIM SEXUAL ASSAULT,0.06,0.02,0.04,0.05,0.04,0.04,0.03,0.04,0.03,0.03,...,0.03,0.03,0.02,0.03,0.05,0.03,0.03,0.03,0.03,0.01
CRIMINAL DAMAGE,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,...,0.04,0.04,0.03,0.03,0.04,0.04,0.03,0.03,0.03,0.02
CRIMINAL TRESPASS,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.04,0.04,0.03,...,0.03,0.04,0.04,0.03,0.03,0.04,0.04,0.03,0.03,0.02
DECEPTIVE PRACTICE,0.04,0.04,0.03,0.03,0.03,0.04,0.03,0.03,0.03,0.03,...,0.03,0.03,0.03,0.03,0.03,0.04,0.03,0.03,0.03,0.03
GAMBLING,0.07,0.03,0.02,0.01,0.03,0.02,0.03,0.03,0.05,0.04,...,0.02,0.02,0.01,0.04,0.03,0.01,0.02,0.03,0.03,0.03
HOMICIDE,0.02,NaN,0.03,0.02,0.06,0.03,0.02,0.08,0.05,0.05,...,0.02,0.03,0.03,0.03,0.03,0.03,0.02,0.02,0.03,0.02
HUMAN TRAFFICKING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.50,NaN,NaN,NaN,NaN
INTERFERENCE WITH PUBLIC OFFICER,0.03,0.02,0.05,0.03,0.02,0.04,0.04,0.05,0.04,0.05,...,0.04,0.03,0.02,0.03,0.04,0.03,0.04,0.03,0.03,0.01
INTIMIDATION,0.02,0.04,NaN,0.04,0.02,0.04,0.02,0.02,0.04,0.06,...,NaN,0.04,NaN,0.07,NaN,0.11,0.04,0.02,0.04,0.02
KIDNAPPING,0.02,0.04,0.02,0.04,0.09,0.02,NaN,0.02,NaN,0.02,...,NaN,0.09,0.02,0.06,0.04,0.09,0.02,NaN,0.04,NaN
LIQUOR LAW VIOLATION,0.02,0.05,0.05,0.02,0.02,0.01,0.04,0.01,0.07,0.04,...,NaN,0.01,NaN,0.06,NaN,0.05,0.06,0.02,0.01,NaN
MOTOR VEHICLE THEFT,0.03,0.03,0.04,0.03,0.02,0.04,0.03,0.03,0.03,0.03,...,0.03,0.03,0.04,0.03,0.03,0.03,0.03,0.03,0.04,0.02
NARCOTICS,0.04,0.03,0.04,0.03,0.03,0.04,0.03,0.03,0.03,0.03,...,0.04,0.03,0.03,0.04,0.03,0.03,0.03,0.03,0.03,0.03
NON-CRIMINAL,NaN,NaN,NaN,NaN,NaN,0.12,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.25,NaN,NaN,0.12,NaN,0.12
NON-CRIMINAL (SUBJECT SPECIFIED),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OBSCENITY,0.14,NaN,0.05,0.10,NaN,0.05,NaN,NaN,NaN,NaN,...,0.05,NaN,0.05,0.05,0.10,0.10,0.05,0.05,0.05,0.05
OFFENSE INVOLVING CHILDREN,0.06,0.03,0.04,0.04,0.03,0.02,0.03,0.04,0.03,0.04,...,0.03,0.02,0.02,0.03,0.02,0.04,0.03,0.02,0.04,0.02
OTHER OFFENSE,0.04,0.03,0.03,0.03,0.03,0.04,0.04,0.03,0.03,0.03,...,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.02
PROSTITUTION,0.06,0.01,0.02,0.01,0.02,0.02,NaN,0.08,0.01,0.03,...,0.03,0.06,0.03,0.03,0.04,0.05,0.03,0.05,0.09,0.01
PUBLIC INDECENCY,NaN,NaN,NaN,0.20,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PUBLIC PEACE VIOLATION,0.03,0.04,0.03,0.05,0.03,0.05,0.03,0.04,0.05,0.03,...,0.01,0.03,0.05,0.02,0.04,0.03,0.04,0.02,0.03,0.01
ROBBERY,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.04,0.04,...,0.04,0.03,0.03,0.03,0.04,0.04,0.03,0.04,0.04,0.02
SEX OFFENSE,0.03,0.04,0.01,0.04,0.03,0.03,0.04,0.03,0.03,0.04,...,0.04,0.03,0.03,0.04,0.01,0.01,0.05,0.03,0.03,0.02
STALKING,0.06,0.07,0.06,0.06,NaN,0.06,NaN,0.04,0.04,NaN,...,NaN,0.09,0.06,0.02,0.07,NaN,0.04,0.04,0.02,NaN
THEFT,0.03,0.04,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.04,...,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.02
WEAPONS VIOLATION,0.03,0.03,0.03,0.04,0.04,0.03,0.03,0.03,0.03,0.03,...,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.04,0.03,0.02